### ISSUE TITLE
Issue with Code Insertion Position and Log Line Number Updates in Plugin

### ISSUE THREAD

**Issue by tgxhx** [bg-omar/consolelogger#8]
Hello, I am a user of this plugin, and it's very good as it meets my needs. However, I've encountered a few minor issues. Could you fix them?
![image](https://github.com/bg-omar/consolelogger/assets/5463739/1bf1f1c2-6e6a-40a2-bf96-174cfb250690)
![image](https://github.com/bg-omar/consolelogger/assets/5463739/65d762f1-be0d-43d7-8a9a-5d2415c4e073)

1. Please refer to the screenshot above. When I select the function name and invoke the plugin, the inserted code appears on the second line, whereas it is expected to be on the fourth line because the print function should come after the function, not within it.

![image](https://github.com/bg-omar/consolelogger/assets/5463739/323c7297-b27e-4c05-878b-230bcd9f581c)
![image](https://github.com/bg-omar/consolelogger/assets/5463739/b9fdf4b5-38f7-49ea-a4d7-b72f57e29406)

2. Please refer to the screenshot above. If I select a parameter of an arrow function and invoke the plugin, the inserted code appears on the ninth line, whereas it is expected to be on the seventh line. This is because the print statement for the function's parameter should be inside the function.

![image](https://github.com/bg-omar/consolelogger/assets/5463739/47a4a0b2-315a-4a43-972a-39ce0c409b73)

3. Please refer to the screenshot above. If the print template uses the LN keyword to output line numbers, when a variable is selected and the function is called multiple times, the actual line numbers are incorrect.
4. From point 3, another issue can be observed. If the plugin is used to log a function and later the code is changed causing the function's line numbers to change, and then the plugin is invoked again, it can be seen that the line numbers in the previous log have not been updated. I wonder if this issue can be resolved?

Thank you for taking the time to review these issues. I appreciate the effort you put into maintaining and improving this plugin. Your prompt attention to these matters is highly valued, and I look forward to seeing the enhancements in future updates. Your hard work makes a significant difference to all of us users. Thanks again for your support and dedication.

**Comment by bg-omar** [comment]
I just released version 0.0.29 and I hope I fixed the issues mentioned above. Ive added the option to refresh line numbers using (ctrl + alt + ` )

**Comment by bg-omar** [comment]
Closing this bug
